### ISSUE TITLE
Display page switcher at the top of the posts

### ISSUE THREAD

**Issue by carun** [CyberShadow/DFeed#94] opened 2018-01-03 22:52 UTC
At present a ribbon with the first, prev, number of pages, next and last is being  displayed at the bottom of the page. It would be very helpful if this can be displayed at the top as well. 
![image](https://user-images.githubusercontent.com/471374/34543453-b6a1a470-f095-11e7-909e-9c3c3c140957.png)

**Comment by CyberShadow** [comment] 2018-01-03 23:44
Duplicate of #16.

**Closed by CyberShadow** 2018-01-03 23:44 UTC
